// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77Voncd59q2kUV88boCzq3lzdIBlbP_w',
    appId: '1:693723954073:web:7aadfecddc6f4ef0d63108',
    messagingSenderId: '693723954073',
    projectId: 'electivagrupo2-54703',
    authDomain: 'electivagrupo2-54703.firebaseapp.com',
    storageBucket: 'electivagrupo2-54703.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5yiDPsYolrknDF1YEw5F0q1l91QzbYjw',
    appId: '1:693723954073:android:e5f1eb80927e635fd63108',
    messagingSenderId: '693723954073',
    projectId: 'electivagrupo2-54703',
    storageBucket: 'electivagrupo2-54703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQJaXRmptyUALmFgpQG_KGTLFUAHEpfQ',
    appId: '1:693723954073:ios:42e585ade40d4e45d63108',
    messagingSenderId: '693723954073',
    projectId: 'electivagrupo2-54703',
    storageBucket: 'electivagrupo2-54703.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQJaXRmptyUALmFgpQG_KGTLFUAHEpfQ',
    appId: '1:693723954073:ios:42e585ade40d4e45d63108',
    messagingSenderId: '693723954073',
    projectId: 'electivagrupo2-54703',
    storageBucket: 'electivagrupo2-54703.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA77Voncd59q2kUV88boCzq3lzdIBlbP_w',
    appId: '1:693723954073:web:ca1dc9341385af6dd63108',
    messagingSenderId: '693723954073',
    projectId: 'electivagrupo2-54703',
    authDomain: 'electivagrupo2-54703.firebaseapp.com',
    storageBucket: 'electivagrupo2-54703.firebasestorage.app',
  );
}
